services:
 nginx:
  build: nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "8282:80"
 php:
  build: php
  container_name: php
  hostname: php
  volumes:
    - ../Api:/var/www

  working_dir: /var/www/public
  command: php-fpm
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
    PHP_IDE_CONFIG: serverName=localhost

 mongo:
    image: mongo
    restart: always
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

 mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/   
 client:
  image: nginx
  container_name: client
  hostname: client
  ports:
    - 8080:80
  volumes:
    - ../Preview:/usr/share/nginx/html

    
